-- CRIAR TABELA CLIENTE
CREATE TABLE CLIENTE(
    ID_CLIENTE NUMBER NOT NULL
    ,NOME VARCHAR2(200) NOT NULL
    ,CPF VARCHAR2(11) NOT NULL
    ,GENERO VARCHAR2(5) NULL
    ,ANO_NASC VARCHAR2(4) NOT NULL
    ,CONSTRAINT PK_CLIENTE PRIMARY KEY ( -- CRIANDO UMA CHABE PRIMARIA
    ID_CLIENTE
    )
    ENABLE
    );


-- CRIAR UMA SEQUENCIA PARA O ID_CLEINTE DA TABELA CLIENTE
CREATE SEQUENCE S_ID_CLIENTE
  INCREMENT BY 1 START WITH 1 MINVALUE 1;

-- CRIAR UMA TRIGGER DE AUTO INCREMENTO NO ID_CLIENTE DA TABELA CLIENTE
CREATE OR REPLACE TRIGGER T_ID_CLIENTE
BEFORE INSERT ON CLIENTE
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_CLIENTE IS NULL THEN
            SELECT S_ID_CLIENTE.NEXTVAL INTO :NEW.ID_CLIENTE FROM DUAL;
        END IF;
    END IF;
END;

-- CRIAR TABELA CONTATO COM CHAVE PRIMARIA PARA ID_CONTATO
CREATE TABLE CONTATO (
    ID_CONTATO NUMBER NOT NULL
    ,EMAIL VARCHAR2(100) NOT NULL
    ,DDD VARCHAR2(3) NOT NULL
    ,TELEFONE VARCHAR2(11) NOT NULL
    ,CONSTRAINT PK_CONTATO PRIMARY KEY (ID_CONTATO) ENABLE
);

-- CRIAR SEQUENCIA PARA O ID_CONTATO DA TABELA CONTATO
CREATE SEQUENCE S_ID_CONTATO
    INCREMENT BY 1 START WITH 1 MINVALUE 1;

-- CRIAR AUTO INCREMENTO PARA ID_CONTATO DA TABELA CONTATO
CREATE OR REPLACE TRIGGER T_ID_CONTATO
    BEFORE INSERT ON CONTATO
        FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_CONTATO IS NULL THEN
            SELECT S_ID_CONTATO.NEXTVAL INTO :NEW.ID_CONTATO FROM DUAL;
        END IF;
    END IF;
END;

-- CRIAR TABELA ENDERECO COM CHAVE PRIMARIA PARA ID_ENDERECO
CREATE TABLE ENDERECO(
    ID_ENDERECO NUMBER NOT NULL
    ,CEP VARCHAR2(10) NOT NULL
    ,RUA VARCHAR2(200) NOT NULL
    ,NUMERO VARCHAR2(10) NOT NULL
    ,BAIRRO VARCHAR2(50) NOT NULL
    ,CIDADE VARCHAR2(50) NOT NULL
    ,ESTADO VARCHAR(2) NOT NULL
    ,CONSTRAINT PK_ENDERECO PRIMARY KEY (ID_ENDERECO) ENABLE
);
-- CRIAR SEQUENCIA PARA O ID_ENDERECO DA TABELA ENDERECO
CREATE SEQUENCE S_ID_ENDERECO
    INCREMENT BY 1 START WITH 1 MINVALUE 1;

-- CRIAR AUTO INCREMENTO PARA ID_ENDERECO DA TABELA ENDERECO
 CREATE OR REPLACE TRIGGER T_ID_ENDERECO
 BEFORE INSERT ON ENDERECO
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_ENDERECO IS NULL THEN
            SELECT S_ID_ENDERECO.NEXTVAL INTO :NEW.ID_ENDERECO FROM DUAL;
        END IF;
    END IF;
END;

-- INLCUIR COLUNA ID_CLIENTE EM CONTATO
ALTER TABLE CONTATO
ADD ID_CLIENTE NUMBER NOT NULL;

-- INLCUIR COLUNA ID_CLIENTE EM ENDERECO
  ALTER TABLE ENDERECO
ADD ID_CLIENTE NUMBER NOT NULL;

-- CRIAR FOREIGN KEYS EM CONTATO E ENDERECO
ALTER TABLE CONTATO
ADD CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE);

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ID_CLIENTE2 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE);
